def imprimir_analisis(local, visitante, liga, sim, stats_a=None, stats_b=None):
    print("\n" + "=" * 60)
    print(f"  🏆 {liga}")
    print(f"  ⚽  {local}  vs  {visitante}")
    print("=" * 60)

    print("\n┌─────────────────────────────────────────┐")
    print("│           RESULTADO FINAL 1X2           │")
    print("├─────────────────────────────────────────┤")
    print(f"│  {local[:20]:<20} {sim['prob_local']*100:>6.1f}%  │")
    print(f"│  Empate                      {sim['prob_empate']*100:>6.1f}%  │")
    print(f"│  {visitante[:20]:<20} {sim['prob_visitante']*100:>6.1f}%  │")
    print("└─────────────────────────────────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│           DOBLE OPORTUNIDAD             │")
    print("├─────────────────────────────────────────┤")
    print(f"│  1X (Local o Empate)         {sim['prob_1x']*100:>6.1f}%  │")
    print(f"│  X2 (Empate o Visitante)     {sim['prob_x2']*100:>6.1f}%  │")
    print(f"│  12 (Local o Visitante)      {sim['prob_12']*100:>6.1f}%  │")
    print("└─────────────────────────────────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│             AMBOS MARCAN                │")
    print("├─────────────────────────────────────────┤")
    print(f"│  SI                          {sim['prob_ambos_marcan']*100:>6.1f}%  │")
    print(f"│  NO                          {(1-sim['prob_ambos_marcan'])*100:>6.1f}%  │")
    print("└─────────────────────────────────────────┘")

    if stats_a and stats_b:
        print("\n┌─────────────────────────────────────────────────────┐")
        print("│              TIROS AL ARCO Y TOTALES                │")
        print("├──────────────────────┬──────────────┬───────────────┤")
        print("│  EQUIPO              │  AL ARCO     │  TOTALES      │")
        print("├──────────────────────┼──────────────┼───────────────┤")
        print(f"│  {local[:20]:<20} │  {stats_a['tiros_arco_favor']:>6.2f}      │  {stats_a['tiros_arco_favor']:>6.2f}        │")
        print(f"│  {visitante[:20]:<20} │  {stats_b['tiros_arco_favor']:>6.2f}      │  {stats_b['tiros_arco_favor']:>6.2f}        │")
        print("└──────────────────────┴──────────────┴───────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│          OVER / UNDER GOLES             │")
    print("├──────────┬──────────────┬───────────────┤")
    print("│  LINEA   │    OVER      │    UNDER      │")
    print("├──────────┼──────────────┼───────────────┤")
    for linea, vals in sim["goles_ou"].items():
        print(f"│  {linea:<8} │  {vals['over']*100:>6.1f}%    │   {vals['under']*100:>6.1f}%     │")
    print("└──────────┴──────────────┴───────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│         OVER / UNDER CORNERS            │")
    print("├──────────┬──────────────┬───────────────┤")
    print("│  LINEA   │    OVER      │    UNDER      │")
    print("├──────────┼──────────────┼───────────────┤")
    for linea, vals in sim["corners_ou"].items():
        print(f"│  {linea:<8} │  {vals['over']*100:>6.1f}%    │   {vals['under']*100:>6.1f}%     │")
    print("└──────────┴──────────────┴───────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│        OVER / UNDER TARJETAS            │")
    print("├──────────┬──────────────┬───────────────┤")
    print("│  LINEA   │    OVER      │    UNDER      │")
    print("├──────────┼──────────────┼───────────────┤")
    for linea, vals in sim["tarjetas_ou"].items():
        print(f"│  {linea:<8} │  {vals['over']*100:>6.1f}%    │   {vals['under']*100:>6.1f}%     │")
    print("└──────────┴──────────────┴───────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│           MARCADOR EXACTO               │")
    print("├─────────────────────────────────────────┤")
    for marcador, prob in sim["marcadores_prob"]:
        print(f"│  {marcador:<10}                  {prob:>5.1f}%  │")
    print("└─────────────────────────────────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│          RESULTADO POR MITADES          │")
    print("├─────────────────────────────────────────┤")
    print(f"│  1T Local                    {sim['prob_1t_local']*100:>6.1f}%  │")
    print(f"│  1T Empate                   {sim['prob_1t_empate']*100:>6.1f}%  │")
    print(f"│  1T Visitante                {sim['prob_1t_visitante']*100:>6.1f}%  │")
    print(f"│  2T Local                    {sim['prob_2t_local']*100:>6.1f}%  │")
    print(f"│  2T Empate                   {sim['prob_2t_empate']*100:>6.1f}%  │")
    print(f"│  2T Visitante                {sim['prob_2t_visitante']*100:>6.1f}%  │")
    print("└─────────────────────────────────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│             HANDICAP 3-WAY              │")
    print("├─────────────────────────────────────────┤")
    print(f"│  Local -1                    {sim['prob_hcp_local_m1']*100:>6.1f}%  │")
    print(f"│  Empate -1                   {sim['prob_hcp_empate_m1']*100:>6.1f}%  │")
    print(f"│  Visitante -1                {sim['prob_hcp_visit_m1']*100:>6.1f}%  │")
    print(f"│  Local +1                    {sim['prob_hcp_local_p1']*100:>6.1f}%  │")
    print(f"│  Empate +1                   {sim['prob_hcp_empate_p1']*100:>6.1f}%  │")
    print(f"│  Visitante +1                {sim['prob_hcp_visit_p1']*100:>6.1f}%  │")
    print("└─────────────────────────────────────────┘")

    print("\n┌─────────────────────────────────────────┐")
    print("│              PROYECCIONES               │")
    print("├─────────────────────────────────────────┤")
    print(f"│  Goles: {sim['goles_local_proj']:.2f} - {sim['goles_visitante_proj']:.2f}                     │")
    print(f"│  Corners totales:    {sim['corners_totales_proj']:.2f}                 │")
    print(f"│  Tarjetas totales:   {sim['tarjetas_totales_proj']:.2f}                 │")
    print("└─────────────────────────────────────────┘")
